# Generated by Django 3.1.1 on 2022-06-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_dataforalgorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataforalgorithm',
            name='hashsum',
            field=models.ForeignKey(db_column='hashsum', on_delete=django.db.models.deletion.CASCADE, to='lending.users'),
        ),
    ]
